package com.yallina.myapplication.data.local_db.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import org.threeten.bp.LocalDateTime
import com.yallina.myapplication.domain.model.Task

/**
 * Room Task Entity that is used to store and retrieve data from Room DataBase
 * @param id unique [Task] identifier, will be auto generated by Room
 * @param name represents [Task]'s name
 * @param description represents [Task]'s description
 * @param dateStart represents [Task]'s starting date
 * @param dateEnd represents [Task]'s closing date
 */
@Entity(tableName = "tasks")
data class TaskEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    @ColumnInfo(name = "name") val name: String,
    @ColumnInfo(name = "desc") val description: String?,
    @ColumnInfo(name = "date_start") val dateStart: LocalDateTime?,
    @ColumnInfo(name = "date_end") val dateEnd: LocalDateTime?
)
